<?php
/**
 * (c) CupcakePHP: The Rapid and Tasty Development Framework.
 *
 * PHP version 5.5.12
 *
 * @author  Ge Bender <gesianbender@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT License
 * @version GIT: <git_id>
 * @link    http://cupcake.simplesys.com.br
 */
?>
<div class="alert alert-info"><button type="button" class="close" data-dismiss="alert">×</button><?php echo $bemVindo ?></div>

           <div class="sortable row-fluid">
				<a data-rel="tooltip" title="Nova locação" class="well span3 top-block" href="<?php echo $index; ?>pedidos/cliente">
					<span class="icon32 icon-green icon-plus"></span><br/>
					<span>Novo pedido</span>
				</a>

				<a data-rel="tooltip" title="Locações a entregar" class="well span3 top-block" href="#">
					<span class="icon32 icon-blue icon-arrowthick-n"></span><br/>
					<span>A entregar</span>
					<span class="notification blue">7</span>
				</a>

				<a data-rel="tooltip" title="Alugadas em dia" class="well span3 top-block" href="#">
					<span class="icon32 icon-orange icon-bullet-on"></span><br>
					<span>Em dia</span>
					<span class="notification yellow">34</span>
				</a>

				<a data-rel="tooltip" title="Locações a retirar" class="well span3 top-block" href="#">
					<span class="icon32 icon-red icon-arrowthick-s"></span><br>
					<span>A retirar</span>
					<span class="notification red">3</span>
				</a>
			</div>
<!--
			<div class="row-fluid sortable">
				<div class="box span4">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Atividades recentes</h2>
					</div>
					<div class="box-content">
						<div class="box-content">
							<ul class="dashboard-list">
								<li>
									<a href="#">
										<img class="dashboard-avatar" alt="Usman" src="http://www.gravatar.com/avatar/<?php echo md5( strtolower( trim( "usman@halalit.net" ) ) ); ?>.png?s=50"></a>
										<strong>Cliente:</strong> <a href="#">Usman
									</a><br>
									<strong>DAta:</strong> 17/05/2012<br>
									<strong>Serviço:</strong> <span class="label label-success">Entrega</span>
								</li>
								<li>
									<a href="#">
										<img class="dashboard-avatar" alt="Sheikh Heera" src="http://www.gravatar.com/avatar/<?php echo md5( strtolower( trim( "heerasheikh@ymail.com" ) ) ); ?>.png?s=50"></a>
										<strong>Cliente:</strong> <a href="#">Sheikh Heera
									</a><br>
									<strong>Data:</strong> 17/05/2012<br>
									<strong>Serviço:</strong> <span class="label label-warning">Renovação</span>
								</li>
								<li>
									<a href="#">
										<img class="dashboard-avatar" alt="Abdullah" src="http://www.gravatar.com/avatar/<?php echo md5( strtolower( trim( "abdullah123456@abc.com" ) ) ); ?>.png?s=50"></a>
										<strong>Cliente:</strong> <a href="#">Abdullah
									</a><br>
									<strong>Data:</strong> 25/05/2012<br>
									<strong>Serviço:</strong> <span class="label label-important">Retirada</span>
								</li>
								<li>
									<a href="#">
										<img class="dashboard-avatar" alt="Saruar Ahmed" src="http://www.gravatar.com/avatar/<?php echo md5( strtolower( trim( "saruarall@gmail.com" ) ) ); ?>.png?s=50"></a>
										<strong>Cliente:</strong> <a href="#">Saruar Ahmed
									</a><br>
									<strong>Data:</strong> 17/05/2012<br>
									<strong>Serviço:</strong> <span class="label label-info">Atendimento</span>
								</li>
							</ul>
						</div>
					</div>
				</div>

				<div class="box span4">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-list-alt"></i> Distribuição das caçambas</h2>
					</div>
					<div class="box-content">

<script type="text/javascript">
$(function () {
    var data = [
        {label: "Em dia: 10%", data:10},
        {label: "A entregar: 20%", data: 20},
        {label: "A retirar: 30%", data: 30},
        {label: "Livres: 40%", data: 40}
    ];

    var options = {
            series: {
                pie: {show: true}
                    }
         };

    $.plot($("#flotcontainer"), data, options);
});
</script>


<div id="legendPlaceholder"></div>
<div style="width: 100%;height: 200px;text-align: left;" id="flotcontainer"></div>

					</div>
				</div>

				<div class="box span4">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-list"></i> Estatísticas da semana</h2>
					</div>
					<div class="box-content">
						<ul class="dashboard-list">
							<li>
								<a href="#">
									<i class="icon-arrow-up"></i>
									<span class="green">92</span>
									Locações
								</a>
							</li>
						  <li>
							<a href="#">
							  <i class="icon-arrow-down"></i>
							  <span class="red">15</span>
							  Retiradas
							</a>
						  </li>
						  <li>
							<a href="#">
							  <i class="icon-retweet"></i>
							  <span class="blue">36</span>
							  Renovações
							</a>
						  </li>
						  <li>
							<a href="#">
							  <i class="icon-comment"></i>
							  <span class="yellow">45</span>
							  Atendimentos
							</a>
						  </li>
						  <li>
							<a href="#">
							  <i class="icon-ok"></i>
							  <span class="green">112</span>
							  Recebimentos
							</a>
						  </li>
						  <li>
							<a href="#">
							  <i class="icon-plus-sign"></i>
							  <span class="red">12</span>
							  Novos clientes
							</a>
						  </li>
						  <li>
							<a href="#">
							  <i class="icon-minus"></i>
							  <span class="blue">13%</span>
							  Variação nas locações
							</a>
						  </li>
						  <li>
							<a href="#">
							  <i class="icon-comment"></i>
							  <span class="yellow">27%</span>
							  Variação no faturamento
							</a>
						  </li>
						</ul>
					</div>
				</div>

			</div>
 -->