<?php if ($v->hasNoVisibleElements() === false)    { ?>

        <hr>

        <div class="modal hide fade" id="myModal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Settings</h3>
            </div>
            <div class="modal-body">
                <p>Here settings can be configured...</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Close</a>
                <a href="#" class="btn btn-primary">Save changes</a>
            </div>
        </div>

        <footer>

        <div class="left" style="margin-left: 20px;">
            Um produto <a href="http://www.simplesys.com.br/" target="_blank"><b>Simplesys</b></a><br/>
            &copy; Copyright <?php echo date('Y'); ?>

        </div>
        <div style="width: 35px;" class="center"><i class="responsive-icon"></i></div>
        <div class="right" style="margin-right: 20px;">
            Templates <a target="_blank" href="http://usman.it/free-responsive-admin-template">Charisma</a><br/>
            By <a target="_blank" href="http://usman.it" target="_blank">Muhammad Usman</a>
        </div>

        </footer>
<?php } ?>

<div class="loading-modal"></div>
<div class="history-main-content"></div>

    <script type="text/javascript" src="<?php echo $v->getWeb(); ?>charisma/js/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $v->getWeb(); ?>js/jquery/maskedinput.js"></script>
    <script type="text/javascript" src="<?php echo $v->getWeb(); ?>js/jquery/maskMoney.min.js"></script>
    <!-- <script type="text/javascript" src="<?php echo $v->getWeb(); ?>js/jquery/jquery.validate.js"></script> -->

    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery-ui-1.8.21.custom.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-transition.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-alert.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-modal.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-dropdown.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-scrollspy.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-tab.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-tooltip.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-popover.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-button.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-collapse.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-carousel.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-typeahead.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/bootstrap-tour.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.cookie.js"></script>
    <script src='<?php echo $v->getWeb(); ?>charisma/js/fullcalendar.min.js'></script>
    <script src='<?php echo $v->getWeb(); ?>charisma/js/jquery.dataTables.min.js'></script>

    <!-- chart libraries start -->
    <script src="<?php echo $v->getWeb(); ?>charisma/js/excanvas.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.flot.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.flot.pie.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.flot.stack.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.flot.resize.min.js"></script>
    <!-- chart libraries end -->

    <script src="<?php echo $v->getWeb(); ?>charisma/js/chosen.jquery.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.uniform.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.colorbox.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.cleditor.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.noty.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.elfinder.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.raty.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.iphone.toggle.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.autogrow-textarea.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.uploadify-3.1.min.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/jquery.history.js"></script>
    <script src="<?php echo $v->getWeb(); ?>charisma/js/charisma.js"></script>

    <div class="noty_bar noty_theme_default noty_layout_top noty_error hide" id="naoImplementado" style="cursor: pointer;"><div class="noty_message"><span class="noty_text noty_error_msg"></span></div></div>

    <script type="text/javascript" src="<?php echo $v->getWeb(); ?>js/simplesys.js?v=<?php echo time(); ?>"></script>

    <?php if($alert !== false) { ?>
    <script>
    $(document).ready(function() {
    	CupcakeAlert('<?php echo $alert; ?>');
    });
    </script>
    <?php } ?>

    <?php if ($topFull !== false) { ?>
        <button class="noty" style="display: none;" id="top-full-call" data-noty-options='{<?php echo $topFull; ?>}'></button>
        <script>
        $(document).ready(function() {
            $('#top-full-call').click();
        });
        </script>
    <?php } ?>

</body>
</html>