<?php if ($v->hasNoVisibleElements() === false)	{ ?>

			<!-- left menu starts -->
			<div class="span2 main-menu-span">
				<div class="well nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li class="nav-header hidden-tablet">Capital Caçambas</li>
						<li><a href="<?php echo $index; ?>"><i class="icon-home"></i><span class="hidden-tablet"> Painel</span></a></li>
						<li><a class="" href="<?php echo $index; ?>clientes"><i class="icon-tags"></i><span class="hidden-tablet"> Clientes</span></a></li>
						<li><a class="" href="<?php echo $index; ?>pedidos"><i class="icon-flag"></i><span class="hidden-tablet"> Pedidos</span></a></li>
						<li><a class="" href="#"><i class="icon-briefcase"></i><span class="hidden-tablet"> Financeiro</span></a></li>
						<li><a class="" href="<?php echo $index; ?>equipamentos"><i class="icon-inbox"></i><span class="hidden-tablet"> Equipamentos</span></a></li>
						<li><a class="" href="<?php echo $index; ?>caminhoes"><i class="icon-road"></i><span class="hidden-tablet"> Caminhões</span></a></li>
						<li><a class="" href="<?php echo $index; ?>produtos"><i class="icon-barcode"></i><span class="hidden-tablet"> Produtos</span></a></li>
						<li class="nav-header hidden-tablet">Configurações</li>
						<li><a class="" href="<?php echo $index; ?>tipos-equipamento"><i class="icon-cog"></i><span class="hidden-tablet"> Tipos de Equipamento</span></a></li>
<!-- 						<li><a class="Cupcake-nav" href="#"><i class="icon-eye-open"></i><span class="hidden-tablet"> Faturamento</span></a></li> -->
						<li><a href="#"><i class="icon-off"></i><span class="hidden-tablet"> Sair</span></a></li>
					</ul>
					<!-- <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox"> Ajax on menu</label> -->
				</div><!--/.well -->
			</div><!--/span-->
			<!-- left menu ends -->

			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>

<?php } ?>